### ISSUE TITLE
[UI 기획] 게임UI 기획 알파용

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#15]
## focus
----
- 알파버전용 UI 기획입니다. [링크](https://docs.google.com/presentation/d/1qiPWlCajaYItoG6Zo_OfZREVyWHPnlQKETtbSxbq2Ss/edit#slide=id.p)

**Comment by kyungho-lee** [comment]
전체 화면연결을 만들어봤습니다. 참고하세요.
https://docs.google.com/presentation/d/1qiPWlCajaYItoG6Zo_OfZREVyWHPnlQKETtbSxbq2Ss/edit#slide=id.g827e4f5604_1_73

**Comment by naratteu** [comment]
이게임은 스테이지 해금식으로 알고있는데 새게임과 계속하기를 구분할 이유가 있나요?

**Comment by naratteu** [comment]
사용할수있는 리소스 경로도 ppt에 포함되면 좋을거같아요

**Comment by bana0731** [comment]
> 사용할수있는 리소스 경로도 ppt에 포함되면 좋을거같아요

방금 ppt에 경로적었습니다.
