### ISSUE TITLE
[Alpha 1.0]툰드라 레벨_stage01 개발가이드

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#16]
## focus
- 레벨의 스테이지 1에 대한 구성을 합니다. 이미지 참조
![image](https://user-images.githubusercontent.com/15261449/77600542-9b7b4980-6f4b-11ea-9771-d3ce4c00b6a0.png)

**Comment by kyungho-lee** [comment]
@baw6114 님 스테이지 제작시 아트리소스 추가하거나 기능제작에 추가해야 되는 부분이 있으면 @devjjoa 님과 협업 부탁드립니다.

**Comment by baw6114** [comment]
Develop Branch의 'Art/PolygonVikings/Maps/PenguinMap_kj' 경로입니다.

**Comment by kyungho-lee** [comment]
@baw6114 개선사항적용을 위해 해당 이슈는 FGT 마일스톤으로 까지로 연장합니다.
