### ISSUE TITLE
[Cinematic/Cut Scene/Video]

### ISSUE THREAD

**Issue by Kohemi** [kyungho-lee/1603SP5#18]

**Comment by naratteu** [comment]
로고 동영상 만들어주세요

![SHANA Untitled_2020-04-04_07-05-57](https://user-images.githubusercontent.com/10435867/78409762-740c3700-7645-11ea-9781-2cbdc42e82ec.gif)

**Comment by Kohemi** [comment]
https://drive.google.com/file/d/1TmuEEaMUK89vNu8pSOdmnTiX7wqUXfOz/view?usp=sharing

위 주소에 영상 업로드 했습니다.

@naratteu
