### ISSUE TITLE
[Alpha1.0] 유닛시스템

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#2]
## Focus
-  유닛은 플레이어가 목표지점까지 호위해야하는 게임토큰으로 작동한다. 직접적인 제어를 할 수 없고 주변사물이나 환경을 캐릭터의 능력으로 가이드할 수 있다. 유닛은 상황에 따라 상태가 전환되기도 하며 외부환경과 인터렉션해서 피해를 받는다. 

## definition
- 유닛 (Unit) : 게임내 플레이어가 직접 제어할 수 없는 액터로 주변환경과 상호작용한다. 대부분의 상호작용을 통해 피해를 받는다. 
- 스폰(spawn) : 유닛이 등장하는것 (개수를 지정할 수 있다.)
- 리젠(regen) : 액션오브젝트가 초기위치에 다시 나타나는 것 (리젠되기 전에 delay 타임이 있음)
- 리더유닛 (Leader unit) : 유닛들이 follow하는 액터
- Spot : 플레이어가 해결해야 하는 미션이 있는 구간
- 스프라인(spline) : 리더유닛이 이동하는 기준이 되는 라인 (여러개가 있을수 있다.) 

## policy
- 유닛은 N(100)의 그룹으로 되어있다. 
- 유닛은 보이지 않는 leader 유닛을 follow하는 형태이다.
- 리더유닛(Leader unit)은 스프라인(splines)을 따라 이동한다. 
- 스플라인(Spline)은 레벨제작시 레벨제작시 배치한다. (스플라인은 상황에 따라 여러개가 될 수 있다.)
- 유닛은 start spot 에서 시작한다. (1차로 플레이어도 인접위치에서 시작한다. )
- 유닛은 플레이어가 게임스타트버튼을 누른 후 N(5)초 후 출발한다.
- ~~유닛은 지정된 spot 단위로 이동하며 spot에 도착하면 상태가 변경될 수 있다.(계속이동/대기/경로변경)~~ : 상태변경은 2차
- ~~유닛은 플레이어 인터렉션에 따라 트리거 작동이나, 특정한 범위내에서 행동이 정해진다. (논의필요)~~ 
   - ~~예: 이동불가지역A spot에 도착시 이벤트가 해결되기까지 대기상태가 된다.~~
   - ~~예2: 물에 빠지는 지역 B spot 에 도착시 유닛이 물에 떠있는 상태로 대기 상태가 된다.~~ 
- 유닛에 효과가 발생하거나 연출되는 부분은 유닛정보에 포함된다. (개발파트에서 설계)
- 유닛은 특정범위에서 이동속도가 느려지거나 빨라질 수 있다 
- 유닛은 HP를 가진다. (HP 정도에 따라 쉐이더효과를 변화시켜 정보를 준다.) 
- spot 구간을 지나면 HP는 회복된다.
- 게임모드에 따라 유닛이 피해를 주는 형태가 될 수 있다. (산사태, 눈덩이, 거대운석이 굴러감)
     - 목표지점으로 이동하는 것은 동일.
- 정책외에 추가로 필요한 예외사항이나 데이터구조는 개발파트에서 제안한다. @baw6114 

## spec
- [x] 유닛 스타트spot spawn (spawn후 딜레이시간: 커스텀)
- [x] 유닛이동 (목표지점) : LeaderUnit 이 Splines를 따라 이동, 유닛들은 LeaderUnit을 follow 합니다.
- [ ] ~~유닛 상태전환 (이동, 대기, 슬로우)~~
- [ ] 유닛삭제처리 (오브젝트와 인터렉션시 dead 상태: 이펙트연출) 
- [x] 유닛카운트 (디폴트수 : 커스텀) 현재보유량
- [x] 유닛 모듈화 (유닛의 외형이 다를 수 있다.)

## display
![DokiDokiEarthProtect_start_유닛](https://user-images.githubusercontent.com/15261449/78618134-8809a000-78b4-11ea-9753-5cabf3eaaeb2.jpg)

**Comment by baw6114** [comment]
유닛 스타트spot 리젠 (리젠후 딜레이시간: 커스텀) - 리젠 > 스폰이 맞는 것 같습니다.
 유닛이동 (목표지점) : Splines를 따라 이동 - Splines를 따라 이동 > Learder를 따라 이동
 유닛 상태전환 (이동, 대기, 슬로우) - 미구현
 유닛삭제처리 (오브젝트와 인터렉션시 dead 상태: 이펙트연출) - 죽는 상태는 있으나 연출은 아직 미구현
 유닛카운트 (디폴트수 : 커스텀) 현재보유량 - 미구현
 유닛 모듈화 (유닛의 외형이 다를 수 있다.) - 구현 Leader에서 설정

**Comment by kyungho-lee** [comment]
@baw6114 현재 유닛 시스템 구현상황 다시한번 공유주세요.
- [ ] 유닛삭제처리 (오브젝트와 인터렉션시 dead 상태: 이펙트연출) @Kohemi 님과 협업
