### ISSUE TITLE
[Alpha 2.0] 레벨01_스테이지02 맵제작

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#20]
focus
- 레벨1_스테이지02를 제작합니다.

참고링크
https://docs.google.com/spreadsheets/d/1sIcDPN5beHQE0hppTa9zj3VE7m-peDcIMH7b_on5w0o/edit#gid=284407969

![image](https://user-images.githubusercontent.com/58926271/77725627-461d6600-7039-11ea-92f4-dad7fef89c1d.png)

2스테이지 동선

![image](https://user-images.githubusercontent.com/58926271/77725666-64836180-7039-11ea-9445-8c00a4020e7a.png)
출발선선

![image](https://user-images.githubusercontent.com/58926271/77725762-a57b7600-7039-11ea-97aa-9ad4d8e32846.png)
스팟1 - 눈내리는지역 
눈내리는 지역 - 데미지 입는 눈이나 비로 만들어주세요

![image](https://user-images.githubusercontent.com/58926271/77725838-dbb8f580-7039-11ea-84e8-ef192db1af6f.png)
스팟2 - 구멍을 매움, 매운 구멍위로 펭귄이 지나갈 수 있음

![image](https://user-images.githubusercontent.com/58926271/77726104-7e717400-703a-11ea-9637-fadc5b1b87a5.png)
스팟3 - 폭탄을 던져 앞의 얼음기둥 4개를 없애 주세요.

![image](https://user-images.githubusercontent.com/58926271/77727679-305e6f80-703e-11ea-890e-724f1db64f22.png)
스팟4 - 동굴 종유석 잘라서 길 만들기

![image](https://user-images.githubusercontent.com/58926271/77727754-5421b580-703e-11ea-8e1f-6d4140f3d88f.png)
스팟5 - 퓅귄 풍선 매다는 구간

![image](https://user-images.githubusercontent.com/58926271/77727915-aebb1180-703e-11ea-822b-69f419a40e4e.png)
도착 지점

**Comment by devjjoa** [comment]
레벨 1 스테이지2 구간 레벨 디자인 완료
총 5개 스팟 구간 설정

**Comment by kyungho-lee** [comment]
툰드라레벨 02스테이지 더미제작은 완료로 클로즈합니다. 수정은 별도 이슈로 처리합니다.
