### ISSUE TITLE
[Alpha 2.0] 포레스트레벨_스테이지01 맵제작

### ISSUE THREAD

**Issue by seok7115** [kyungho-lee/1603SP5#24]
## focus
- 레벨2을 제작합니다.
- 여자아이를 곰을 피해 안전지역까지 이동하는 미션
- 맵테스트 후 추가 수정 진행

## 플레이 시나리오 

1. 어린여자아이는 플레이어지점에 위치한 상태로 시작 플레이 화면에 보이고 여자아이 뒷편앵글에서 맵에 시작점위치에  떨어진 곰을 발견하고 카운터 후 플레이가 시작한다.
![image](https://user-images.githubusercontent.com/58921136/78733100-6c1f0080-797f-11ea-9855-0c7ca613b523.png)

2. 여자아이는 도망을 가게 되고 여자아이가 이동되는 예상되는 경로를 따라 이동하면  첫번째 스팟1(갈림길을) 만나게 되고, 뒤에는 계속 곰이 따라 온다. 캐릭터가 지나가게 한 후 스팟1에 있는 통나무를 이용하여 캐릭터가 지나간 후 맹수의 이동경로를 막아야 한다. 곰의 이동경로를 막게 되면 3초후 곰은 사라진다.
(스팟1, 통나무 배치 ,캐릭터 행동 나무를 들어 지정 위치에 나무 배치)

3. 스팟 1을 클리어하게 되면 길을 따라 스팟 지역 10으로 이동하게 된다. 스팟 2은 사거리가 나타나며 그 곳에서는 이정표가 길옆에 있으며, 이정표를 캐릭터가 방향을 바꿀 수 있다. 이정표가 가리키는 방향으로 여자아이는 이동하게 되며, 선택에 따라 왔던길로 다시가거나, 막다른길로 빠지게 되거나, 다음 스팟진행 되는 길로 진행할 수 있다.
(스팟2. 길가에 이정표 배치, 캐릭터는 이정표 방향을 틀 수 있다. 여자아이가 이정표 방향에 따라 이동 하게 된다.)
  
3. 스팟 3 에서도 4거리가 있으며, 스팟 2과 마찬가지로 이정표가 길가에 배치 되어 있다. 이곳에는 호박이 길위에 놓여져 있으며, 부서진 
호박은 사라지고 열린 길로 유닛은 이동 할 수 있다. 

3-1. 호박이 사라진 후 3초뒤 스팟3지역에서 곰이 나타나게 된다.

4. 스팟 4에 진입하면 두갈래 길에는 나무가 쓰러져 있으며, 스팟1과 동일한 미션으로 나무를 들어 유닛을 이동시키고 따라오는 곰을 막으면 미션 성공되고, 곰은 3초뒤 사라지게 된다.

5. 스팟 5,6  중간 지역에  여자아이가 지나간 후 3초후 곰은 발생되며, 곰은 여자아이을 따라오고 스팟6에 나무에 달려 있는 벌통을 지나가게 된다. 캐릭터는 벌통을 마법을 이용하여 곰이 지나가기 직전 벌통을 맞춰 떨어뜨리면, 곰은 그것에 관심을 가지고 이동하게 되고 여자아이는 스팟7 지역까지 이동한다.
(스팟5과 스팟6 지역 사이 여자아이가 지나간 후 3초의 딜레이 후 곰 발생, 스팟2지역 벌통 배치, 벌통을 맞추는 마법 또는 주변 물체를 던져 맹수가 지나가는 타이밍에 맞춰 벌통에 이동하게 만들기)
 
6. 스팟7에서는 중간에 다리가 끊긴 강이 있으며, 주변에 세워져 있는 나무를 잘라내 나무를 보강하여 다리를 이어 만드는 미션, 다리가 다 만들어 질때 까지 유닛은 스팟3에서 대기, 다리가 다 만들어지면 강위로 지나 갈 수 있다. 스팟6에서 벌통으로 시간 벌기 했던 곰은 벌통이 자동으로 사라지고, 여자아이가 있는 방향으로 다가오게 되며, 그 시간 동안 나무 다리를 만드는 미션, 다리를 만들기 위해서는 주변에 특정 큰 나무를 3개 필요하며, 3개를 자른 후 이동시켜  특정위치에 자른 나무 배치 하면 다리가 완성 유닛이 지나가며, 맹수가 그위를 지나가면 , 가라앉게 된다.

7. 스팟9는 돌무더기로 가로 막혀 있으며, 캐릭터의 물방울,또는 풍선 마법으로 돌무더기를 띄워서 치울 수 있다. 길이 뚫리게 되면 처음 시작한 플레이어지점으로 이동하게 된다.

## 스팟별 플로우

> 스팟 1컨셉 : 흐름제어, 타이밍 (여자아이를 지나가게 한 후 곰이 다가오는 것을 막음) 

1. 스팟에 도착 길 앞에 나무가 가로 막혀 있음 (여자아이가 이동할 수 있게 나무를 치움
2. 뒤에서는 여자아이를 향해 다가오는 곰이 있음 
3. 여자아이가 나무를 치운 곳을 지나간 후 곰이 지나가기전 다시 나무로 길을 막음
4. 여자아이는 스팟1을 지나가면 이동이 막힌 곰은 3초가 지나면 제거됨
5. 미션 실패시 곰은 여자아이를 향해 계속 전진 접촉시 게임 실패 조건

> 스팟 2 컨셉 : 곰을 피해 스팟2에 도착했다면 이정표를 이용한 플레이어의 방향 선택을 요구 

1. 스팟 2 길앞엔 표지판이 있으며, 표지판에 방향에 따라 여자아이는 방향을 진행 할 수 있는 구간
2. 방향이 선택되면 여자아이는 그 방향에 따라 이동하게 되며, 다음 스팟으로 이동하게 된다.
3. 선택된 길이 막다른 길에 들어서게 되고 막다른 길로 갔을경우 길로 이동하는 중간에 여자아이 뒤에서 곰이 나타나 결국 호수에 빠지게 되어 여자아이는 죽게 된다.

> 스팟 4 컨셉  : 갈림길에서 다시 곰이 나타나고 이번엔 이정표를 빠르게 선택한 후 여자아이가 이동하면, 여자아이가 지나간 후 곰과의 사이에 나무를 이동시켜 접근을 차단 

1. 갈림길에 여자아이가 도착한다.
2. 도착함과 동시에 뒤에서 곰이 나타난다.
3. 캐릭터는 빠르게 길을 선택 후에 여자아이가 선택된 길로 이동하게 되면 곰과 사이에 나무를 놔 이동을 방해 한다.
4.곰의 이동경로를 막으면 3초뒤에 곰은 사라진다.
5.이동경로를 막지 못하면 계속 곰은 여자아이를 뒤따라 오게 된다.
6. 따라오는 곰이 여자아이 접촉시 게임이 끝난다.

> 스팟6 컨셉 : 스팟7에서 스팟2로 지나가는 길에 다시 여자아이 뒤에서 곰이 나타나고, 여자아이는 스팟6를 지나가고 뒤에 곰이 따라오는 타이밍에 꿀벌집을 맞춰 곰의 환심을 끌어 시간을 버는 구간

1. 스팟5과 스팟6 지역 사이 특정구간을 여자아이가 지나간 후 3초의 딜레이 후 곰 발생
2. 곰을 다시 여자아이를 쫒아오며, 여자아이는 스팟2 구간을 지나가게 되고 스팟2에 있는 나무위에 벌통을 캐릭터가 물체를 던져 벌통을 떨어뜨린 후 곰이 발견하게 되면, 곰은 벌통에 관심을 유도하는 장치가 된다.

>스팟7 컨셉 : 강이 있는 구간에 다리가 끊겨 있으며, 주변의 나무를 잘라내 나무를 보강해 다리를 이어 만들고 여자아이가 지나가게 하는 미션 

1.여자아이가 스팟3에 도착하면 다리가 끊겨 있어 앞으로 이동할 수 없다.
2.주변의 나무를 자르고 이동시켜 나무 다리를 만든다. 3개의 나무가 필요 그사이 스팟2에서 벌통이 3분뒤 사라지고 벌통이 사라진 곰은 여자아이쪽으로 다가온다.
3.끊긴다리위 특정위치에 자른 나무가 배치되면 여자아이는 그위로 이동하게 되고 여자아이가 지나간 후, 곰이 그위로 지나가면 곰은 떨어지게 되며 사라진다.  
4. 다리를 건넌 여자아이는 안전지역으로 이동 미션 클리어 지역 도착

>스팟9 컨셉 기타  : 작은 돌무더기로 길이 막혀 있는 구간 돌무더기를 캐릭터의 물방울 마법을 이용하여 돌이 이동시켜 막고 있던 돌이 없어지며 사라지는 미션

1.스팟 9지역은 여자아이 앞에 돌무더기가 길을 가로막고 있으며, 돌을 
캐릭터의 마법인 물방울 마법을 이용에 돌을 띄울 수가 있다. 
2.띄워진 돌은 공중으로 뜨게 되고 10초후 사라진다.
3.길이 개방되며, 다시 처음 시작된 곳으로 길이 시작되게 된다.

**Comment by kyungho-lee** [comment]
피드백
1. 시작시 캐릭터 위치와 유닛의 위치 천적(?)의 위치관계가 명확하지 않습니다. 어느방향의 50m인지 몰라서 맵상에 시작점이면 맵밖에서 보인다는 의미인지 , 그렇다면 해당맵의 표현은 전체맵이 아니라 플레이 일부분만 표현된건지 부터가 애매합니다. (이부분은 제작된 맵에서 직접 표시를 해주는게 좋을것 같습니다.)

2. 스테이지 목표, 유닛종류, 천적,  사용오브젝트,  캐릭터액션종류등을 focus나 기능요소라고 플레이시나리오 전에 써주시면 좋을것 같습니다.

**Comment by kyungho-lee** [comment]
@seok7115 님 FGT 마일스톤전까지 기획이 완료되어야 alpha 2.0 4월9일까지 개발이 가능할것 같습니다. 참고해주세요.,
