### ISSUE TITLE
[Alpha 2.0]시나리오 스타트 디스플레이 플로어

### ISSUE THREAD

**Issue by seok7115** [kyungho-lee/1603SP5#27]
지구의 선한 에너지에 의해 탄생한 포리는 어릴때부터 지구 환경 보호 교육을 받고 자라난 요정은 당연하게 그것을 따르고 실천한다. 
그러던 어느 날 지구가 멸망하는 예지몽 꾸게 되고, 그 꿈에 지구 멸망을 막기 위해 살려야 하는 필요 한 동물과 사람, 반드시 성공해야 하는 이벤트들을 (신의 계시)꿈에 포리에게 알려준다. 포리가 사랑하는 이 지구, 지구멸망을 막기 위해 자신이 사랑하고 관심을 가진 존재들을 다치지 않게 하고 보호하기 위해 포리는 바로 잠에서 깨어 일어나고, 여행이 시작된다....(크레딧)?

화면 구성
지구 전체 화면이 나오고, 
지구의 선한 에너지가 모이는 장면,
그 선한 에너지 속에 포리가 탄생하는 장면,
포리는 누군가에 의해 지구환경 보호 교육을 받는 장면,
어느날 숲 속 나뭇잎을 이불삼아 자고 있는 포리 장면,
지구가 검은 지구가 돼 망한 지구가 망한 효과의 장면,
(하얀 빛 ,신) 같은 존재가 있고 그 아래 있는 포리, 이렇게 곧 지구가 멸망하게 되니 막기 위해 필요한 살려야 하는 동물,사람,이벤트등을 알려주고 그것을 듣고 있는 포리 장면,
나뭇잎에서 자고 있던 포리는 눈을 뜨고 바로 일어나서 이동하는 포리의 모습 장면.
(포리가 날라가면서 빠르게 이동하는 모습 화면에서 사라짐)
[스타트_디스플레이_플로어_초안.pptx](https://github.com/kyungho-lee/1603SP5/files/4453550/_._._.pptx)

**Comment by devjjoa** [comment]
![image](https://user-images.githubusercontent.com/58926271/78852641-d86d3300-7a57-11ea-8e8b-da8bb70c0348.png)
![image](https://user-images.githubusercontent.com/58926271/78852644-ddca7d80-7a57-11ea-995e-f0654ec61114.png)
![image](https://user-images.githubusercontent.com/58926271/78852651-e15e0480-7a57-11ea-9f63-d0f481023c36.png)

**Comment by devjjoa** [comment]
인트로 이미지 제작 - 완료
