### ISSUE TITLE
[캐릭터 기능 개발] 집기 시스템 개선

### ISSUE THREAD

**Issue by baw6114** [kyungho-lee/1603SP5#29]
- 다리 및 들어올리는 오브젝트의 상태 고정 필요 (Rotation 및 Location의 고정)

- 집어서 내려놓는 오브젝트의 내려놓는 위치를 표시하는 시스템 필요

- 내려놓는 위치가 캐릭터와 너무 가까운 경우 충돌이 발생 위치 수정 필요

**Comment by baw6114** [comment]
![떨어지는Location표시테스트(미완)](https://user-images.githubusercontent.com/34436162/78498585-29460880-7786-11ea-8e10-842e9fddd5c9.png)

떨어지는 위치표시 아직 미완성/ 들어올렸을 때 위치 및 회전은 고정상태

**Comment by baw6114** [comment]
![떨어지는Location표시완료](https://user-images.githubusercontent.com/34436162/78500642-a6777a80-7792-11ea-9e7a-07d4c7c0b719.png)
떨어지는 위치 표시 완료

**Comment by kyungho-lee** [comment]
이슈 클로즈 합니다. 추가 이슈 발생하면 생성
