### ISSUE TITLE
[art resource]캐릭터 기술별 아이콘제작

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#33]
# focus
- 기능아이콘 리스트 입니다.
- 샘플은 Soma라는 게임에 있는 액션아이콘 입니다. 컨셉을 따라할 필요는 없고 심플하게 텍스트와 함께 플레이어가 인지할 수 있는 아이콘이면 됩니다.

## display
- 현재 더미로 구현한 화면
![DokiDokiEarthProtect_구멍메우기_spot1](https://user-images.githubusercontent.com/15261449/78617143-5e9b4500-78b1-11ea-9ca7-da2ab4d4b803.jpg)

## 일반 
----
1. 대기 (Idle_icon)
   설명 : 대기상태 AIM 아이콘
 
![수정됨_crosshair_default_large_clear](https://user-images.githubusercontent.com/15261449/78525944-84720c80-7813-11ea-82d8-552bb78ac4c6.jpg)
  
2. 이동불가(blockarea_icon)
   설명 : 이동 불가지역 아이콘
 
![수정됨_crosshair_talk_busy](https://user-images.githubusercontent.com/15261449/78526119-ff3b2780-7813-11ea-9bfd-5c2f10708b9a.jpg)

## 액션
---- 

 액션 1. 들기  (Lift_action_icon)
     설명 :  오브젝트 부양이동 (자석이동 느낌,중력없음) #21
 ![수정됨_crosshair_pull_vertical](https://user-images.githubusercontent.com/15261449/78525699-dfefca80-7812-11ea-80b8-e380d52476b9.jpg)

 액션 2. 당기기(Pull_action_icon)
     설명 : 오브젝트 attach로 끌어서 위치이동 (버튼 물건올려놓기,중력작용) #22

![수정됨_crosshair_pull_door](https://user-images.githubusercontent.com/15261449/78526074-de72d200-7813-11ea-82c7-5af02dfe6099.jpg)

 액션 3. 던지기(throw_action_icon)
     설명 : 오브젝트 던지기 (중력건스타일) 멀리있는 타겟형태의 버튼작동 #

![image](https://user-images.githubusercontent.com/15261449/78530824-509ce400-781f-11ea-99b4-f5382fa8cf05.png)

 액션 4. 밀기 (Pull_action_icon)
     설명 : 오브젝트와 충돌해서 밀기 (마찰력 무시, 컬링효과) 마우스컨트롤 없음
![수정됨_crosshair_push](https://user-images.githubusercontent.com/15261449/78526305-9a340180-7814-11ea-9083-7eb8eba8361a.jpg)

 액션 5. 폭탄 (Bomb_action_icon)
      설명 : 폭탄 던지기 (중력건 + 시한폭탄) #10
![image](https://user-images.githubusercontent.com/15261449/78527654-8094b900-7818-11ea-9173-8a8b42ee247d.png)

 액션 6.  자르기(Cutting_action_icon)
      설명 : 오브젝트 자르기 (밧줄끊기, 물건자르기) #3
![image](https://user-images.githubusercontent.com/15261449/78528876-64464b80-781b-11ea-804e-06c1ee5216e3.png)

 액션 7.  비눗방울 (Bubble_action_icon)
      설명 : 비눗방울을 던져 맞추면 공중에 띄우기 액션 (중력건 + 풍선효과) #14 
![image](https://user-images.githubusercontent.com/15261449/78529049-bdae7a80-781b-11ea-8e60-ae71432f422b.png)

 액션 8.  풍선 (balloon_action_icon)
       설명 :  오브젝트에 풍선을 생성해 공중에 띄우기 액션 (자르기 + 풍선달기) #13
![image](https://user-images.githubusercontent.com/15261449/78528924-7de79300-781b-11ea-8274-7cc48eee0df3.png)

## 레퍼런스
![image](https://user-images.githubusercontent.com/15261449/78526485-1d555780-7815-11ea-8c35-42345c555fd7.png)

![image](https://user-images.githubusercontent.com/15261449/78526633-93f25500-7815-11ea-8a42-cd930dc9469d.png)

**Comment by kyungho-lee** [comment]
추가 아이콘 @bana0731 

- 툰드라 레벨/stage 2

- 방사능상태아이콘 (state_radiation_icon)
설명) 펭귄 산성비 보호에서 펭귄이 비를 맞으면 위기표시 노란색 느낌표 (방사능표시?)
![image](https://user-images.githubusercontent.com/15261449/78622822-256ad100-78c1-11ea-9453-4a7c2b4fa0d4.png)

- 위험상태아이콘 (state_death_icon)
설명) 펭귄 산성비 보호에서 펭귄이 위험상태 (해골마크/ 붉은색 계열)
![image](https://user-images.githubusercontent.com/15261449/78622766-fd7b6d80-78c0-11ea-8c00-9e6c67d3a589.png)

- 회복상태아이콘 (state_heart_icon)
설명) 펭귄이 체력 회복상태 (하트)
![image](https://user-images.githubusercontent.com/15261449/78622940-72e73e00-78c1-11ea-8d01-a7f419ef1a05.png)

**Comment by bana0731** [comment]
액션 손동작 아이콘만 제작완료.

**Comment by bana0731** [comment]
일반- 대기,이동불가 아이콘 제작완료.

**Comment by bana0731** [comment]
![balloon_action](https://user-images.githubusercontent.com/58926230/78633691-2c074180-78dd-11ea-937f-9eac2a6bbb8d.png)
![blockarea](https://user-images.githubusercontent.com/58926230/78633693-2d386e80-78dd-11ea-9714-91ce2c3b2b2f.png)
![Bomb_action](https://user-images.githubusercontent.com/58926230/78633694-2dd10500-78dd-11ea-88d6-81df08557dbe.png)
![Bubble_action](https://user-images.githubusercontent.com/58926230/78633695-2dd10500-78dd-11ea-9211-d503f0c3adfc.png)
![Cutting_action](https://user-images.githubusercontent.com/58926230/78633698-2e699b80-78dd-11ea-8f3c-35e792f450fb.png)
![Idle](https://user-images.githubusercontent.com/58926230/78633699-2e699b80-78dd-11ea-82c0-3a359ea56fdf.png)
![Lift_action](https://user-images.githubusercontent.com/58926230/78633700-2f023200-78dd-11ea-88f8-7795fcbc987d.png)
![Pull_action](https://user-images.githubusercontent.com/58926230/78633701-2f9ac880-78dd-11ea-9560-923d713333b0.png)
![Push_action](https://user-images.githubusercontent.com/58926230/78633704-2f9ac880-78dd-11ea-9e3f-782422d4f1a5.png)
![throw_action](https://user-images.githubusercontent.com/58926230/78633705-30335f00-78dd-11ea-96b4-49c0222fb8f3.png)
03.resource\08.UI\캐릭터기술아이콘

**Comment by bana0731** [comment]
파일경로-03.resource\08.UI\캐릭터기술아이콘
![state_heart](https://user-images.githubusercontent.com/58926230/78645357-64654a80-78f2-11ea-90a7-52a215f0818c.png)
![state_radiation](https://user-images.githubusercontent.com/58926230/78645360-64fde100-78f2-11ea-8b04-1774c0b0a643.png)
![state_death](https://user-images.githubusercontent.com/58926230/78645363-65967780-78f2-11ea-964b-9202efc0c5eb.png)

**Comment by kyungho-lee** [comment]
작업완료/ 추가 작업이 필요하면 별도 이슈로 처리합니다.
