### ISSUE TITLE
[기능구현] 액션아이콘 적용

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#38]
## focus
----
- 제작된 액션 아이콘과 텍스트를 적용합니다.

## 액션아이콘 리스트

- [x] 들기(Lift) : 일정 높이 이상 들어서 놓을 수 있는 액터.
- [x] 당기기 (Pull) : 끌어서 당길수 있는 액터
- [x] 던지기 (Throw) : 캐릭터 앞에 들고 멀리 던질 수 있는 액터 (카메라 앵글변화)
- [x] 밀기 (Push) : 캐릭터가 충돌해서 밀수 있는 액터.
- [x] 폭탄 던지기 (Bomb throw) : 캐릭터 앞에 들고 던질 수 있는 폭탄 액터 (카메라 앵글변화)
- [x] 자르기 (Cutting) : 캐릭터앞에 자를 수 있는 액터가 생성되고 맞으면 잘리는 액터 (카메라 앵글변화)
- [x] 버블던지기 (Bubble throw) : 캐릭터 앞에 들고 타겟을 향해 쏘는 액터 (카메라 앵글변화)
- [x] 풍선던지기 (Balloon throw) : 캐릭터앞에 던질 수있는 이펙트가 생성되고 날아가서 맞으면 풍선이 생성되는 액터 (카메라 앵글변화)

**Comment by kyungho-lee** [comment]
관련이슈 #33

**Comment by baw6114** [comment]
UI 아이콘 적용 완료
