### ISSUE TITLE
[UI] 화면플로우 

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#4]
## focus
-----
게임 플레이 화면구성을 작성합니다.
각 화면별 러프한 UI 기능도 포함 합니다.

참고자료)

## work flow작업순서
1. 게임플로우에 따른 화면플로우 작성
2. 캐릭터 설정에 따른 정보 표시
3. 플레이 설정에 따른 정보 표시
4. 컨셉에 맞게 디자인
5. 연출 및 개선

게임화면 플로우
1. 로고 (팀로고)
2. 타이틀 (press anybutton)
3. 스테이지선택
4. 인게임(Ready)
5. 인게임 UI
6. credit

화면플로우
----

![image](https://user-images.githubusercontent.com/15261449/78380465-dd248800-760e-11ea-9f06-11e3b9395dc6.png)

**Comment by kyungho-lee** [comment]
한번봐주셈

**Comment by devjjoa** [comment]
https://docs.google.com/presentation/d/1qiPWlCajaYItoG6Zo_OfZREVyWHPnlQKETtbSxbq2Ss/edit?usp=sharing

UI 제작 문서 기획서 링크 했습니다.
