### ISSUE TITLE
[bug]툰드라 레벨 스팟 3에서 오류

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#44]
# 상태
- 던지기 스팟에서 화면에 구체가 하나 떠있게 되고 해당 오브젝트에 걸려서 유닛이 이동못하는 상태 발생

![image](https://user-images.githubusercontent.com/15261449/78735250-45fc5f00-7985-11ea-856b-a49ec5f04c29.png)

# 상태2
- 천적과 충돌해서 모두 죽었는데도 재시작이 안되는 현상

## 개선사항
- 던지기 속도와 파워가 너무 약함. 조정하는 방법을 알려주세요.

**Comment by baw6114** [comment]
구체는 초기 유령 상태일 때 빙의 되었던 폰이 남았던 것으로 확인
현재 튜토리얼 맵에서는 안나타나게 완료

**Comment by baw6114** [comment]
![image](https://user-images.githubusercontent.com/34436162/78746281-59b5be80-79a1-11ea-984c-f794de00dbcf.png)
그림의 ThrowPower를 조정해서 던지기 힘 조절 가능하게 변경
