### ISSUE TITLE
[UI] 플레이 현재진행위치 상태바

### ISSUE THREAD

**Issue by bana0731** [kyungho-lee/1603SP5#45]
![RoadmMap-preview](https://user-images.githubusercontent.com/58926230/78735730-72fd4180-7986-11ea-8904-2ece2d7d7479.png)
![RoadmMap-preview2](https://user-images.githubusercontent.com/58926230/78735731-74c70500-7986-11ea-9582-de40926a8b00.png)

이미지 파일 경로
03.resource\08.UI\RoadMap

![RoadMap_border](https://user-images.githubusercontent.com/58926230/78735823-a93ac100-7986-11ea-8f75-c5840841b65a.png)
![RoadMap_glitter1](https://user-images.githubusercontent.com/58926230/78735825-aa6bee00-7986-11ea-9018-f524ec27e873.png)
![RoadMap_glitter2](https://user-images.githubusercontent.com/58926230/78735827-aa6bee00-7986-11ea-835a-7038ac3842b0.png)
![RoadMap_penguin](https://user-images.githubusercontent.com/58926230/78735829-ab048480-7986-11ea-9830-2fb5dac7a447.png)
![RoadMap_penguin_glitter](https://user-images.githubusercontent.com/58926230/78735830-ab048480-7986-11ea-9ec6-9a0349989039.png)
![RoadMap_tracking](https://user-images.githubusercontent.com/58926230/78735832-ab9d1b00-7986-11ea-8646-d481791e0201.png)

사이즈 수정사항있으면 알려주세요. #

**Comment by kyungho-lee** [comment]
의견)
- 스타트와 목표지점표시가 있으면 좋겠네요 
- 마리수 표시하는 부분도 있어야 합니다. (팽귄이미지 근처에 표시되면 좋겠네요)

**Comment by bana0731** [comment]
파일경로
03.resource\08.UI\RoadMap

![RoadmMap-preview3](https://user-images.githubusercontent.com/58926230/78951042-a917fe00-7b0b-11ea-8407-6e51a97730f6.png)
![RoadMap_finish](https://user-images.githubusercontent.com/58926230/78951047-acab8500-7b0b-11ea-86a3-7f11ea8cf486.png)
![RoadMap_HeartLabel](https://user-images.githubusercontent.com/58926230/78951051-ae754880-7b0b-11ea-835f-254543a1a4d9.png)
