### ISSUE TITLE
[툰드라 스테이지2] 기능개선사항

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#47]
공통
- 캐릭터가 빠지는 구역이 없어야 합니다.
   - 바닥에 구멍이 있는 지점
   - 동굴에 끊어진 구역
   - 비누방울 스팟에 바다
- 유닛 속도 스테이지 1과 동일하게 
- 실패처리
- 클리어처리

1. 스팟 1 
    - 유닛 상태 변화에 따른 아이콘 표시 (기능구현)  
    - 비오는 구간이 확실히 보이게 (빗물 색상_녹색, 양 많이)변경
    - 구간은 조절 , 다음스팟을 대응할 수 있을 정도

2. 스팟2
    - 눈덩이는 당기기속성으로 설정해서 테스트
    - 미끌어지는 정도를 조절
 
3. 스팟3 
    - 폭탄 리젠 3개다 사용하면 다시 리젠된다.
    - 폭탄 외형 변경 (현재 보유하고 있는 에셋에서 찾기)
    - 던지기 속도 조절

4. 스팟 4
    - 고드름 개수 추가하고 길고 뾰족하게해서 더 많이 자를 수 있게 배치

**Comment by gt3973** [comment]
유닛 속도 조정 
각 맵의 레벨 블루프린트에 들어가서
![image](https://user-images.githubusercontent.com/34848965/78738446-e86c1080-798c-11ea-91a4-0198043dcc6d.png)

**Comment by gt3973** [comment]
레벨에서 BP_Particle_Rain를 찾아서 누르면 
디테일 창에 
Area : 비 내리는 구역 크기
Rain Amount :  비 내리는 양
Rain Speed: 비 내리는 속도
Drop Stop Time : 비 내리는 시간
![image](https://user-images.githubusercontent.com/34848965/78738664-616b6800-798d-11ea-9770-af8943df476c.png)

펭귄들이 데미지를 입는 구간은 
PainCausingVolume의 크기를 조절하면됨
![image](https://user-images.githubusercontent.com/34848965/78738807-bad39700-798d-11ea-8d08-9955e1f1a1e3.png)

**Comment by gt3973** [comment]
왼쪽 3개 당기기 오른쪽 4개 밀기
![image](https://user-images.githubusercontent.com/34848965/78741101-7945ea80-7993-11ea-871f-b4d2d512a1d7.png)

BP_ 블루 프린트 Cube에
![image](https://user-images.githubusercontent.com/34848965/78741173-a2667b00-7993-11ea-8656-490958d4fa70.png)
Physics 부분을 이용하여 밀리는 정도 조절
![image](https://user-images.githubusercontent.com/34848965/78741218-c32ed080-7993-11ea-8fa2-35f5116bda9f.png)

**Comment by gt3973** [comment]
스팟 3 폭탄 1개 터질시 다시 스폰

**Comment by gt3973** [comment]
비 색상은 Raint_Mat 머티리얼 블루 프린트에 가서 베이스 컬러에 연결된 색상을 바꾸면됨

![image](https://user-images.githubusercontent.com/34848965/78751963-1dd52600-79ae-11ea-8f69-6798c9d6e136.png)
