### ISSUE TITLE
[컨셉기획] 컨셉기획 공용문서작업

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#5]
- 컨셉기획을 공용문서로 작업합니다.

문서링크)
https://docs.google.com/presentation/d/1EAry4sVbybdhKfX6dg5AtNblteUG7aYy9jANSKQd9QM/edit?usp=sharing

**Comment by Kohemi** [comment]
3/25일자 캐릭터 컨셉 수정 했습니다.ㅣ
