### ISSUE TITLE
[툰드라스테이지2] spot2, spot3 ,spot4 , spot5개선사항

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#50]
## focus
- 스팟2, 3 수정 내용
![image](https://user-images.githubusercontent.com/15261449/78751702-ae5f3680-79ad-11ea-99b7-9c0f476426d0.png)

- 스팟4 수정내용
![image](https://user-images.githubusercontent.com/15261449/78757262-2e3dce80-79b7-11ea-9aac-b60e6939c9ae.png)

- 스팟5 수정내용
![image](https://user-images.githubusercontent.com/15261449/78756615-09952700-79b6-11ea-8c54-4c584a6d759e.png)

**Comment by devjjoa** [comment]
spot2, spot4 그래픽 이슈 수정 - 완료
