### ISSUE TITLE
[툰드라 스테이지01] spot 3 개선사항

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#52]
이미지 참조
![image](https://user-images.githubusercontent.com/15261449/78754647-ce452900-79b2-11ea-9915-a9f1b8493a7b.png)

펭귄죽음처리 연출
![image](https://user-images.githubusercontent.com/15261449/78756324-8ffd3900-79b5-11ea-8e9c-c5e579c99a36.png)

**Comment by devjjoa** [comment]
담장을 제거하여 곰이 담장을 통과 하지 않도록 수정함 - 완료

**Comment by baw6114** [comment]
펜스 구조 변경
