### ISSUE TITLE
[유닛 시스템] 툰드라 레벨_유닛 삭제 연출 개선

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#53]
## focus
- 유닛 삭제시 상황별로 여러가지 연출이 나옵니다.

## 상황 조건
1. 함정에 빠졌을때
- 몸이 흩어지듯이 사라지는 연출이 나옵니다.
2. 물에 빠졌을때
- 물에 떠내려 가는 연출이 나옵니다.
3. 천적을 만났을때   
- 고기로 변하는 연출이 나옵니다.

**Comment by baw6114** [comment]
- 곰과 닿으면 고기로 변하는 연출 명인씨가 구현 완료
- 물에 떠내려가는 연출 튜토리얼에 적용 완료

**Comment by Kohemi** [comment]
* 1. 함정에 빠졌을 때 몸이 흩어지는 효과 구현 완료
