### ISSUE TITLE
[FGT 테스트] 개선 사항

### ISSUE THREAD

**Issue by baw6114** [kyungho-lee/1603SP5#55]
- [x] 치즈를 던져놓을 위치 명확하게 표시
- [x] 여러 번 플레이를 통해 적절한 던지는 파워의 설정 필요
- [x] 빙하맵에서 고드름 자르는 곳에서 유닛이 낑겨서 아래로 들어가는 현상
- [x] 게임 플레이시 네비 메쉬가 이동함

**Comment by baw6114** [comment]
치즈 던져놓을 위치에 파티클 추가 아직 명확하게 보이진 않음

**Comment by gt3973** [comment]
게임 플레이시 네비 메쉬가 이동함 

- 프로젝트 세팅 > 네비게이션 메시 > 런타임 > 런타임 제네레이션 Dynamic으로 변경해서 해결

**Comment by baw6114** [comment]
치즈를 던져넣을 위치에 화살표와 파티클 표시, 던져넣기 성공시 파티클 색깔이 변하게 설정
