### ISSUE TITLE
[게임타이틀] 두근두근 지구구하기 타이틀 작업

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#65]
## focus
- 게임 제목이 들어가 있는 타이틀 이미지가 필요합니다.

![image](https://user-images.githubusercontent.com/15261449/78971796-4d6b6600-7b47-11ea-9b50-659368a33ce9.png)

**Comment by bana0731** [comment]
![title작업중](https://user-images.githubusercontent.com/58926230/79067420-125d6400-7cfa-11ea-9b9a-98f0cd5a6761.png)
현재 작업중 이미지

**Comment by bana0731** [comment]
타이틀로고 완성
파일경로
03.resource\08.UI\title

![Title](https://user-images.githubusercontent.com/58926230/79085398-63f60500-7d73-11ea-87c7-98cc5dda74d3.png)
![title완료](https://user-images.githubusercontent.com/58926230/79085400-65273200-7d73-11ea-9dbb-e268374f3eb4.png)

**Comment by bana0731** [comment]
ui배경이미지
파일경로
03.resource\08.UI
![IMG_Main](https://user-images.githubusercontent.com/58926230/79087524-7aec2580-7d7a-11ea-9387-e3eec882668a.png)
![IMG_Main-preview](https://user-images.githubusercontent.com/58926230/79087739-3e6cf980-7d7b-11ea-9d22-b8b09b81b5df.png)
