### ISSUE TITLE
[맵수정] 툰드라레벨_stage02_spot02

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#66]
수정내용
-구멍이 있는 스팟에서 플레이어가 이동해야 할 동선을 인지할 수 있게 길형태로  보여줍니다.

![툰드라_stage02_spot02](https://user-images.githubusercontent.com/15261449/78975591-5b24e980-7b4f-11ea-97e2-555b832f73ed.JPG)

**Comment by devjjoa** [comment]
맵수정 완료
