### ISSUE TITLE
[기능개선] 유닛 죽음 연출

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#75]
# focus
- 유닛이 죽음상태중 사라지는 상황일때 연출을 추가합니다.

예외사항
-  물에 떠 있는 연출시에는 N(10)초후 사라지는 연출을 보여 줍니다.

**Comment by baw6114** [comment]
- 고기로 변할 때 추가
- 함정에서 죽을 때 추가
- 비 맞고 죽을 때 추가
- 물에서 죽을 때 추가
