### ISSUE TITLE
[버그] 툰드라리전_스테이지2_스팟4 지역 얼음채우기 오류

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#77]
## 상황
- 고드름을 잘라서 얼음을 채우는 다 채웠는데 펭귄이 빠져서 죽는 상태가 발생
- 3번째 얼음다리에 충돌이 안되고 그냥 빠지는것 발견
![20200413_IngameUI적용_스테이지02 mp4_20200413_201009 133](https://user-images.githubusercontent.com/15261449/79116143-a7c42b00-7dc2-11ea-87d7-65d4389273e9.png)

## 기대상태
- 펭귄이 빠지거나 껴서 게임이 진행되지 않게 방어한다.

**Comment by baw6114** [comment]
수정 완료
