### ISSUE TITLE
[버그] 툰드라지역_스테이지01_spot3 던지기 판정오류

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#79]
- 20200413_UI적용 version
- 던지기 판정이 안되서 게임진행이 불가함
- 범위안에 들어와도 치즈가 계속 리젠됨.
![oCam 13 mp4_20200413_195917 163](https://user-images.githubusercontent.com/15261449/79115564-24eea080-7dc1-11ea-9a13-da81d2aa2183.png)

**Comment by baw6114** [comment]
판정오류 수정 완료
