### ISSUE TITLE
[기능개선] 툰드라리전_스테이지02_개선사항 리스트

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#84]
스팟01
- [x] 스팟1 유닛 데미지나 판정범위을 조정해서 컨트롤을 좀더 많이 할 수 있게 조정 

- [x] 스팟 2 오브젝트를 밀어서 구멍을 메울때 이펙트 추가

- [x] 캐릭터 자르기 액션시 연출추가

- [x] 스팟 5 물방울액션시 터지는 시간 조절

- [x] 스팟 5 보이지 않는 충돌영역 제거

**Comment by baw6114** [comment]
- 보이지않는 충돌영역 제거
