### ISSUE TITLE
[post_production]플레이 영상작업

### ISSUE THREAD

**Issue by kyungho-lee** [kyungho-lee/1603SP5#85]
# focus
- 플레이 영상을 작업합니다.

## 플레이시나리오
- 영상 시간: 5~6
- 오프닝 영상+ 게임UI+ 인게임 게임플레이 (캐릭터 액션위주)
- 오프닝 음성포함, 게임플레이 레벨별 BGM 및 SF 더빙

**Comment by Kohemi** [comment]
https://drive.google.com/file/d/1jqE2p2nI9SKPyGSFynE9sOsmT8-geMG-/view?usp=sharing

영상작업 완료
