### ISSUE TITLE
itch.io 게임 소개 내용

### ISSUE THREAD

**Issue by seok7115** [kyungho-lee/1603SP5#86]
두근두근 지구 구하기 게임은 액션 어드벤처의 게임으로, 귀여운 우리의 캐릭터인 포리가 게임 시작과 함께 다양한 미션을 해결해 나아가는 방식이다. 이 게임의 목표는 지켜야 할 유닛을 안전하게 보호해야 하며, 다양한 행동과 게임 내 다양한 object 배치를 통해 지정 목적지까지 안전하게 이끄는 것이다.

First penguin
현재의 불확실성을 넘어 용감하게 도전하는 선구자가 되는 팀이 되자.

The game to save the Earth is an action-adventure game, in which our cute character Pory solves various missions with the start of the game. The goal of the game is to safely protect units to be followed, and to lead them safely to designated destinations through various actions and various placement of objects in the game.

First penguin
Let's go beyond the current uncertainty and become a pioneer who bravely challenges.

Programmers:
-Hong Seok Chol
-Ki Sung Yeon
-Sung Won Park
Planners:
-Gyeong Ho Lee
-Jae Ho Seok
-Ho Jun Cha
Designers:
-Hyeong Jin Kim
-Myung In Ko
-Sang I Han

**Comment by kyungho-lee** [comment]
Ep.

We are students who learn to make games.
It's a team project game.
It was completed after two weeks of preproduction, production, postproduction with Unreal 4.

I would like to improve the lack of games produced after experiencing the game production process through your comments.


This is not a complete version but a demo version.
Please give us a lot of feedback.
